package pkg_sql

// Define the filterKeys map globally
var (
	filterKeys = map[string]string{
		"[eq]":       " = ",
		"[ne]":       " != ",
		"[gt]":       " > ",
		"[lt]":       " < ",
		"[gte]":      " >= ",
		"[lte]":      " <= ",
		"[like]":     " LIKE ",
		"[and]":      " AND ",
		"[or]":       " OR ",
		"[date]":     " DATE ",
		"[date_gte]": " DATE_GTE ",
		"[date_lte]": " DATE_LTE ",
	}

	reverseFilterKeys = map[string]bool{
		"=":        true,
		"!=":       true,
		">":        true,
		"<":        true,
		">=":       true,
		"<=":       true,
		"LIKE":     true,
		"AND":      true,
		"OR":       true,
		"DATE":     true,
		"DATE_GTE": true,
		"DATE_LTE": true,
	}

	sqlKeywords = map[string]bool{
		"SELECT":               true,
		"INSERT":               true,
		"UPDATE":               true,
		"DELETE":               true,
		"DROP":                 true,
		"UNION":                true,
		"OR":                   true,
		"1=1":                  true,
		"--":                   true,
		";":                    true,
		"/*":                   true,
		"*/":                   true,
		"EXEC":                 true,
		"EXECUTE":              true,
		"DECLARE":              true,
		"xp_cmdshell":          true,
		"sp_":                  true,
		"xp_":                  true,
		"CREATE":               true,
		"ALTER":                true,
		"EXEC sp_":             true,
		"SELECT @@version":     true,
		"INSERT INTO":          true,
		"UPDATE SET":           true,
		"DELETE FROM":          true,
		"DROP TABLE":           true,
		"UNION ALL":            true,
		"ORDER BY":             true,
		"GROUP BY":             true,
		"AND 1=1":              true,
		"1' OR '1'='1":         true,
		"1' OR 1=1 --":         true,
		"1\" OR \"1\"=\"1":     true,
		"1\" OR 1=1 --":        true,
		"' OR 'x'='x":          true,
		"\" OR \"x\"=\"x":      true,
		"' OR 'a'='a' --":      true,
		"\" OR \"a\"=\"a\" --": true,
	}
)
