# Build stage
FROM golang:1.23-rc-alpine3.20 as builder

RUN apk --no-cache add tzdata

WORKDIR /backend

COPY go.mod .

COPY go.sum .

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o server ./cmd/user/main.user.go

FROM alpine as final

COPY --from=builder /backend/server .
COPY --from=builder /backend/public/ /public/
COPY --from=builder /backend/logs/   /logs/

COPY --from=builder /usr/share/zoneinfo /usr/share/zoneinfo

ENV TZ=Asia/Baghdad

RUN apk update
RUN apk add curl
RUN apk add --no-cache ca-certificates

ENTRYPOINT ["/server"]
