package pkg_err

// List of all errors for record in the app
const (
	InternalServerError                                     = "internal server error"
	RouteNotFound                                           = "route not found"
	Unauthorized                                            = "unauthorized"
	SomethingWentWrong                                      = "something went wrong"
	PleaseContactToSupport                                  = "please contact to support"
	RecordNotFound                                          = "record not found"
	RecordNotFoundInX                                       = "record not found in %v"
	XisNotValid                                             = "%v is not valid"
	BindFailed                                              = "bind failed"
	ValidationFailed                                        = "validation failed"
	ValidationForXFailedInX                                 = "validation for %v failed in %v"
	XIsRequired                                             = "%v is required"
	MinimumAcceptedCharacterForXisX                         = "minimum accepted character for %v is %v"
	MaximumAcceptedCharacterForXisX                         = "maximum accepted character for %v is %v"
	AcceptedValueForXAreX                                   = "accepted value for %v are: [%v]"
	InvalidValueDoNotIncludeX                               = "invalid value didn't include %v"
	DuplicateHappened                                       = "duplicate happened"
	XIsAlreadyExist                                         = "%v is already exist"
	ErrorInBindingV                                         = "error in binding %v"
	InvalidXForX                                            = "invalid %v for %v"
	TokenIsNotValid                                         = "token is not valid"
	TokenIsExpired                                          = "token is expired"
	TokenIsRequired                                         = "token is required"
	BasicAuthIsRequired                                     = "basic auth is required"
	BasicAuthInvalid                                        = "basic auth is not valid"
	Forbidden                                               = "forbidden"
	MinimumAcceptedValueForXIsX                             = "minimum accepted value for %v is %v"
	MaximumAcceptedValueForXIsX                             = "maximum accepted value for %v is %v"
	YouDontHavePermission                                   = "you don't have permission"
	PleaseLoginAgain                                        = "please login again"
	TimeoutHappened                                         = "timeout happened"
	TemporaryRedirect                                       = "temporary redirect"
	BadRequest                                              = "bad request"
	XIsUnique                                               = "%v is unique"
	CheckThisXField                                         = "check this %v fields"
	ItHasRelationWithSomeElementSoItIsNotX                  = "it has relation with some element, so it is not %v"
	ForeignKeyError                                         = "foreign key error"
	BadRequestForXInX                                       = "bad request for %v in %v"
	RecordXXNotFoundInX                                     = "record %v:%v not found in %v"
	XNotExist                                               = "%v not exist"
	XIsInactive                                             = "%v is inactive"
	XFailed                                                 = "%v failed"
	YouVeExceededTheRateLimitForRequestsPleaseTryAgainLater = "You've exceeded the rate limit for requests. Please try again later"
)
