// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"GoRestify/domain/base/base_api"
	"GoRestify/domain/base/base_repo"
	"GoRestify/domain/service"
	"GoRestify/internal/core"
)

// Injectors from wire.go:

func InitBaseCityAPI(e *core.Engine) base_api.CityAPI {
	cityRepo := base_repo.ProvideCityRepo(e)
	baseCityServ := service.ProvideBaseCityService(cityRepo)
	cityAPI := base_api.ProvideCityAPI(baseCityServ)
	return cityAPI
}

func InitBaseRegionAPI(e *core.Engine) base_api.RegionAPI {
	regionRepo := base_repo.ProvideRegionRepo(e)
	baseRegionServ := service.ProvideBaseRegionService(regionRepo)
	regionAPI := base_api.ProvideRegionAPI(baseRegionServ)
	return regionAPI
}

func InitBaseRoleAPI(e *core.Engine) base_api.RoleAPI {
	roleRepo := base_repo.ProvideRoleRepo(e)
	baseRoleServ := service.ProvideBaseRoleService(roleRepo)
	roleAPI := base_api.ProvideRoleAPI(baseRoleServ)
	return roleAPI
}

func InitBaseUserAPI(e *core.Engine) base_api.UserAPI {
	userRepo := base_repo.ProvideUserRepo(e)
	baseUserServ := service.ProvideBaseUserService(userRepo)
	userAPI := base_api.ProvideUserAPI(baseUserServ)
	return userAPI
}

func InitBaseAuthAPI(e *core.Engine) base_api.AuthAPI {
	baseAuthServ := service.ProvideBaseAuthService(e)
	authAPI := base_api.ProvideAuthAPI(baseAuthServ)
	return authAPI
}

func InitBasePkgAPI(e *core.Engine) base_api.PkgAPI {
	pkgAPI := base_api.ProvidePkgAPI(e)
	return pkgAPI
}
